'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Download, Building2, Calendar, FileText, Receipt, CreditCard, MessageCircle, Zap, BarChart3, ChevronRight, Link, FlaskConical, Pill, Shield, Heart, Brain, Inbox, Smartphone, Scissors, Calculator, Package, Apple, Watch, Siren, ShieldCheck, Briefcase, Mic, Video, Users, Home, GraduationCap, Database, Sparkles, AlertTriangle, ShoppingCart } from 'lucide-react';

export default function ClinicTutorialInline({ onClose }) {
  const [activeSection, setActiveSection] = useState(null);

  const sections = [
    { icon: Building2, title: 'Configurazione iniziale', color: 'bg-blue-500', content: ['Registrati come clinica su vetbuddy.it', 'Completa il profilo: nome clinica, indirizzo, P.IVA, orari di apertura', 'Carica il logo e le foto della struttura', 'Configura i servizi offerti con prezzi e durata stimata', 'Pilot Milano: Piano Growth gratuito per 90 giorni', 'Piani: Starter \u20AC29/mese, Growth \u20AC69/mese, Pro \u20AC99/mese (IVA esclusa)'], tip: 'Un profilo completo e professionale aiuta i clienti a scegliere la tua clinica.' },
    { icon: Link, title: 'Link di prenotazione diretto', color: 'bg-indigo-500', content: ['Vai su \u201CLink Prenotazione\u201D nel menu laterale', 'Trovi il link personalizzato della tua clinica', 'Condividilo su WhatsApp, social, email o sito web', 'Puoi generare un QR Code da stampare in reception', 'I clienti inviano una richiesta rapida senza registrarsi', 'Le richieste arrivano nella tua agenda e le confermi tu'], tip: 'Il link permette ai clienti di inviare una richiesta rapida. La clinica conferma poi data, orario e disponibilit\u00E0.' },
    { icon: Calendar, title: 'Gestione appuntamenti', color: 'bg-green-500', content: ['Visualizza il calendario dalla dashboard principale', 'Gestisci le viste: giornaliera, settimanale o mensile', 'Clicca su uno slot vuoto per creare un appuntamento', 'Gestisci le richieste in arrivo: accetta, rifiuta o riprogramma', 'Aggiungi note interne per ogni appuntamento'], tip: 'Usa i codici colore per distinguere i tipi di appuntamento e servizio.' },
    { icon: FileText, title: 'Gestione clienti e pazienti', color: 'bg-teal-500', content: ['Accedi a \u201CPazienti\u201D per consultare l\u2019elenco clienti', 'Visualizza la scheda completa di ogni animale', 'Consulta lo storico visite, trattamenti e documenti', 'Importa clienti da file CSV per migrare da altri gestionali'], tip: 'La funzione import CSV consente di migrare dati da altri sistemi in modo semplice.' },
    { icon: FileText, title: 'Documenti e PDF', color: 'bg-amber-500', content: ['Vai a \u201CDocumenti\u201D dalla dashboard', 'Crea documenti: prescrizioni, referti, certificati, vaccinazioni', 'Carica PDF esistenti o genera da template', 'Il documento viene inviato automaticamente via email'], tip: 'I documenti digitali riducono richieste ripetitive e telefonate non necessarie.' },
    { icon: FlaskConical, title: 'Lab Marketplace', color: 'bg-purple-500', content: ['Sfoglia i laboratori partner nel marketplace', 'Crea una richiesta di analisi selezionando paziente ed esame', 'Segui lo stato della richiesta in tempo reale', 'Ricevi il referto, aggiungi note cliniche e pubblica al proprietario'], tip: 'I referti restano riservati fino alla tua revisione.' },
    { icon: Pill, title: 'Ricette Elettroniche (REV)', color: 'bg-emerald-500', content: ['Prepara la bozza con il wizard guidato', 'Completa l\u2019emissione sul portale nazionale (Vetinfo)', 'Registra numero ricetta e PIN in VetBuddy', 'Pubblica al proprietario quando opportuno', 'Audit trail completo di ogni passaggio'], tip: 'VetBuddy prepara e archivia il flusso. L\u2019emissione ufficiale \u00E8 responsabilit\u00E0 del veterinario.' },
    { icon: Heart, title: 'Piani Salute', color: 'bg-rose-500', content: ['Crea programmi di prevenzione strutturati (Cucciolo, Senior, Prevenzione)', 'Personalizza servizi inclusi: visite, vaccini, esami, trattamenti', 'Assegna un piano a un paziente e monitora il progresso', 'Segna i servizi completati con un click', 'Dashboard con statistiche: piani attivi, servizi prossimi 30gg'], tip: 'I piani salute fidelizzano i clienti e generano appuntamenti ricorrenti.' },
    { icon: Inbox, title: 'Team Inbox avanzata', color: 'bg-sky-500', content: ['Gestisci messaggi come ticket: Nuovo, In lavorazione, Risolto', 'Assegna ticket ai membri del team', 'Imposta priorit\u00E0: Bassa, Media, Alta', 'Rispondi usando template rapidi predefiniti', 'Filtra per stato, priorit\u00E0 o messaggi non letti'], tip: 'La Team Inbox aiuta a non perdere nessun messaggio e a coordinare il team.' },
    { icon: Brain, title: 'AI Assistant', color: 'bg-violet-500', content: ['Riassumi Visita: riassunto strutturato dalle note cliniche', 'Scrivi Messaggio: comunicazioni professionali per i proprietari', 'Traduci Note Cliniche: da termini tecnici a linguaggio semplice', 'Risposta Intelligente: risposte ai messaggi dei clienti', 'Copia il risultato con un click'], tip: 'L\u2019AI \u00E8 un assistente: il risultato va sempre rivisto dal medico veterinario.' },
    { icon: Zap, title: 'Automazioni configurabili', color: 'bg-yellow-500', content: ['Follow-up post visita personalizzabili (timing e messaggio)', 'Reminder per vaccini e controlli periodici', 'Configura timing, canale (email/app) e template per ogni automazione', 'Cronologia esecuzioni: vedi quando ogni automazione si \u00E8 attivata'], tip: 'Le automazioni riducono il tempo dedicato alle attivit\u00E0 ripetitive.' },
    { icon: BarChart3, title: 'Dashboard Valore Generato', color: 'bg-cyan-500', content: ['Tempo risparmiato grazie alle automazioni', 'Telefonate evitate e appuntamenti generati', 'Stima del fatturato generato dalla piattaforma', 'Dati aggiornati in tempo reale'], tip: 'La Dashboard Valore ti aiuta a capire il ritorno sull\u2019investimento.' },
    { icon: MessageCircle, title: 'Task Manager Staff', color: 'bg-slate-600', content: ['Visualizza task operativi automatici: follow-up, preventivi, referti lab, passport', 'Crea task manuali per richiami clienti o attivit\u00E0 interne', 'Assegna priorit\u00E0: Alta, Media, Bassa', 'Filtra per priorit\u00E0, staff assegnato o scadenza', 'Segna task come completati'], tip: 'I task automatici aiutano a non dimenticare nessuna attivit\u00E0 operativa importante.' },
    { icon: MessageCircle, title: 'Campagne Clienti', color: 'bg-orange-600', content: ['5 campagne pronte: dentale, vaccini, sterilizzazione, antiparassitari, senior', 'VetBuddy identifica automaticamente i clienti target', 'Anteprima messaggi prima dell\u2019invio', 'Invio Email o WhatsApp con un click', 'Tracking risultati: aperture, click, conversioni'], tip: 'Le campagne mirate aumentano le prenotazioni per servizi specifici.' },
    { icon: MessageCircle, title: 'Mini CRM Proprietari', color: 'bg-cyan-600', content: ['Etichette automatiche: Attivo, Alto Rischio, Promoter, VIP, Inattivo', 'Relationship score (0-100) per ogni cliente', 'Lifetime value (\u20AC) e numero visite totali', 'Filtra clienti per etichetta o score', 'Dashboard CRM insights nella scheda cliente'], tip: 'Il Mini CRM aiuta a identificare i clienti migliori e prevenire abbandoni.' },
    { icon: MessageCircle, title: 'Dimissioni & Follow-up', color: 'bg-green-600', content: ['Crea pacchetto dimissioni dopo visite/chirurgie', 'Inserisci istruzioni dettagliate e terapie', 'Programma follow-up automatici 24h o 48h', 'Template chiamata con domande chiave', 'Genera PDF dimissione per il proprietario'], tip: 'Follow-up strutturati migliorano la soddisfazione clienti e riducono emergenze.' },
    { icon: MessageCircle, title: 'Stock Leggero Vaccini', color: 'bg-purple-600', content: ['Inventario solo vaccini e materiali critici', 'Alert automatici: scorte basse, scadenze 30/60gg', 'Movimenti carico/scarico con storico', 'Tracking lotti, fornitori e ubicazione fisica', 'Export Excel per report'], tip: 'Non \u00E8 un gestionale completo: traccia solo vaccini e materiali essenziali.' },
    { icon: MessageCircle, title: 'Preventivi Online', color: 'bg-blue-600', content: ['Crea preventivo digitale per procedure', 'Invia link sicuro al proprietario', 'Proprietario approva online con firma digitale', 'Tracking stati: Pending, Approved, Rejected', 'Converti preventivo approvato in fattura'], tip: 'Preventivi online accelerano il processo decisionale e riducono telefonate.' },
    { icon: MessageCircle, title: 'Smart Visit Pack', color: 'bg-indigo-500', content: ['Timeline unificata: Check-in \u2192 Questionario \u2192 Visita \u2192 Dimissioni', 'Visualizza tutte le visite di oggi con stati real-time', 'Dashboard con contatori per ogni fase', 'Azioni rapide per ogni fase della visita', 'Tabs: Timeline, Attive, Completate'], tip: 'Smart Visit Pack semplifica la gestione del flusso visite giornaliero.' },
    { icon: Receipt, title: 'Fatturazione Elettronica XML', color: 'bg-red-600', content: ['Genera fatture XML conformi Sistema di Interscambio (SdI)', 'Validazione automatica dati prima dell\'invio', 'Tracciamento stati: Emessa, Inviata, Accettata, Rifiutata', 'Archivio digitale completo con ricerca', 'Export massivo per commercialista'], tip: 'La fattura XML è obbligatoria per legge. VetBuddy automatizza il processo.' },
    { icon: FileText, title: 'Ricette Elettroniche Veterinarie (REV)', color: 'bg-emerald-600', content: ['Prepara bozza con wizard guidato da scheda paziente', 'Collegati al portale nazionale (Vetinfo/RNV) per emissione', 'Registra numero ricetta e PIN in VetBuddy', 'Pubblica al proprietario quando opportuno', 'Audit trail completo: chi, quando, cosa'], tip: 'VetBuddy prepara e archivia. L\'emissione ufficiale è responsabilità del veterinario abilitato.' },
    { icon: MessageCircle, title: 'Microchip & Anagrafe Canina', color: 'bg-blue-600', content: ['Registra microchip con validazione automatica (15 cifre)', 'Genera certificati conformi normative regionali', 'Prepara dati per invio anagrafi (Lombardia, Lazio, etc.)', 'Storico completo per ogni animale', 'Alert microchip non registrati'], tip: 'Ogni regione ha regole diverse. VetBuddy ti guida nella conformità.' },
    { icon: MessageCircle, title: 'Network Specialisti & Referral', color: 'bg-violet-600', content: ['Invia paziente a specialista partner con un click', 'Segui stato referral: Inviato, Visitato, Completato', 'Ricevi aggiornamenti automatici dallo specialista', 'Dashboard reciprocità: chi ti manda più pazienti', 'Costruisci network professionale di fiducia'], tip: 'Il referral tracking migliora la collaborazione tra professionisti e il follow-up pazienti.' },
    { icon: MessageCircle, title: 'Piani Benessere', color: 'bg-rose-600', content: ['Crea abbonamenti mensili/annuali con servizi inclusi', 'Esempio: Piano Cucciolo €39/mese → 3 visite, 2 vaccini, esami base', 'Monitori utilizzo servizi da dashboard dedicata', 'Gestisci rinnovi automatici e promemoria scadenza', 'Genera fatturato ricorrente e prevedibile'], tip: 'I Piani Benessere fidelizzano clienti e stabilizzano il fatturato mensile della clinica.' },

    { icon: FileText, title: 'Consensi Informati Digitali', color: 'bg-blue-700', content: ['Template preconfigurati: chirurgia, anestesia, eutanasia, trattamenti', 'Firma grafometrica o digitale del proprietario', 'Archiviazione legale 10 anni conforme GDPR', 'Genera PDF consenso in 30 secondi', 'Zero carta, massima sicurezza legale'], tip: 'Elimina completamente la carta e velocizza le accettazioni in clinica.' },
    { icon: AlertTriangle, title: 'Malattie Denunciabili', color: 'bg-red-700', content: ['Elenco malattie denunciabili obbligatoriamente (rabbia, tubercolosi, brucellosi)', 'Alert automatici con tempistiche (immediata, 48h, 7gg)', 'Generazione moduli ufficiali ASL e Ministero Salute', 'Tracking denunce inviate e conferme ricevute', 'Zero rischio multe per mancata segnalazione'], tip: 'Obbligo di legge. VetBuddy automatizza tutto il processo per conformità totale.' },
    { icon: Shield, title: 'Integrazione Assicurazioni Pet', color: 'bg-green-700', content: ['Partner integrati: UnipolSai, Allianz, Generali, AXA', 'Invio automatico documenti e fatture all\'assicurazione', 'Tracking stato rimborso per il cliente', 'Dashboard statistiche: richieste approvate, importi', 'Clinica diventa partner convenzionato'], tip: 'Aumenta fatturato clinica e attrae clienti assicurati (mercato in forte crescita).' },
    { icon: AlertCircle, title: 'Farmacovigilanza ADR', color: 'bg-orange-700', content: ['Segnala reazioni avverse farmaci veterinari', 'Form guidato: nome farmaco, lotto, gravità (lieve/moderata/grave)', 'Invio automatico a Ministero Salute entro 15gg (obbligo)', 'Archivio tracciabile completo', 'Conformità normativa automatica'], tip: 'Obbligo legale per reazioni gravi. VetBuddy riduce la burocrazia.' },
    { icon: Plane, title: 'Certificati Sanitari Viaggio', color: 'bg-sky-700', content: ['Wizard guidato per destinazione (UE, UK, USA, Extra-UE)', 'Genera Passaporto Europeo conforme', 'Certificati export paese-specifici', 'Checklist automatica documenti richiesti', 'Velocizza servizio che clienti pagano bene'], tip: 'I certificati viaggio sono un servizio premium. VetBuddy li rende velocissimi.' },
    { icon: FlaskConical, title: 'Integrazione Laboratori IZS', color: 'bg-purple-700', content: ['Connessione Istituti Zooprofilattici Sperimentali regionali', 'Esami obbligatori: rabbia, brucellosi, tubercolosi, leishmaniosi', 'Richieste esami digitali', 'Ricezione referti automatica', 'Riduce burocrazia con enti pubblici'], tip: 'Gli IZS sono laboratori pubblici obbligatori per certi esami. Integrazione semplifica tutto.' },
    { icon: Clock, title: 'Gestione Turni Guardia H24', color: 'bg-indigo-700', content: ['Calendario turni diurni e notturni', 'Alert emergenze push al veterinario di guardia', 'Handoff automatico tra turni', 'Note di consegna tra veterinari', 'Ideale per cliniche con pronto soccorso'], tip: 'Per cliniche premium con servizio H24. Organizzazione turni semplificata.' },
    { icon: Users, title: 'Tracking Crediti ECM', color: 'bg-teal-700', content: ['Monitoraggio 50 crediti ECM/anno obbligatori', 'Alert 60 giorni prima scadenza', 'Integrazione corsi accreditati FNOVI/SCIVAC', 'Dashboard progressione annuale', 'Storico formazione completo'], tip: 'I veterinari devono acquisire 50 crediti/anno. VetBuddy traccia tutto automaticamente.' },
    { icon: Building2, title: 'Multi-Sede & Gestione Catene', color: 'bg-blue-800', content: ['Dashboard consolidato tutte le sedi', 'KPI comparativi: fatturato, pazienti, performance per sede', 'Trasferimento pazienti tra sedi con 1 click', 'Inventario condiviso multi-sede', 'Gestione staff centralizzata'], tip: 'Ideale per catene con 2+ cliniche. Sblocca il segmento enterprise veterinario.' },
    { icon: Smartphone, title: 'App Mobile Nativa iOS & Android', color: 'bg-purple-800', content: ['App separata proprietari: prenotazioni, documenti, chat, VetBuddy Passport', 'App veterinari: visite domiciliari, accesso cartelle offline', 'Push notifications native real-time', 'Geolocalizzazione per visite domiciliari', 'Fotocamera integrata per documenti'], tip: 'Standard di mercato. Senza app mobile, clinica sembra "incompleta" agli occhi dei clienti.' },
    { icon: Scissors, title: 'Gestione Sala Operatoria', color: 'bg-red-800', content: ['Calendario sala operatoria con stati real-time', 'Checklist pre-operatoria automatica (anestesia, consenso)', 'Tracking strumentario sterile per sicurezza', 'Report chirurgici strutturati post-op', 'Follow-up automatico pazienti operati'], tip: 'Le chirurgie sono il servizio più redditizio. Organizzazione perfetta = fatturato massimizzato.' },
    { icon: Calculator, title: 'Integrazione Contabilità', color: 'bg-green-800', content: ['Sync automatico Fatture in Cloud, TeamSystem, Aruba', 'Import movimenti bancari automatico', 'Prima nota generata automaticamente', 'Dashboard fiscale: situazione IVA real-time', 'Export report per commercialista'], tip: 'Risparmio 5-10 ore/mese al commercialista. Dati sempre sincronizzati, zero errori trascrizione.' },
    { icon: Package, title: 'Inventario Farmaci Completo', color: 'bg-orange-800', content: ['Non solo vaccini: farmaci, materiali chirurgici, attrezzature', 'Alert scadenze 30/60gg con notifiche', 'Costo medio ponderato automatico', 'Ricette scaricano inventario automaticamente', 'Report valore magazzino per bilancio'], tip: 'Farmaci = 20-30% costi clinica. Controllo inventario = risparmio immediato e ottimizzazione.' },
    { icon: CreditCard, title: 'POS/Cassa Integrata', color: 'bg-indigo-800', content: ['Integrazione Nexi, SumUp, Stripe Terminal', 'Workflow: visita → pagamento → scontrino/fattura automatica', 'Cassa giornaliera e chiusura turno', 'Riconciliazione automatica con contabilità', 'Zero errori di quadratura'], tip: 'Elimina errori di cassa. Workflow completo end-to-end dalla visita al pagamento.' },
    { icon: BarChart3, title: 'Analytics & BI Avanzati', color: 'bg-cyan-800', content: ['Dashboard drag-drop personalizzabili per ogni ruolo', 'Report custom: fatturato per servizio, veterinario, trend', 'Benchmark anonimo vs altre cliniche italiane', 'Previsioni AI fatturato con machine learning', 'Export automatico report mensili via email'], tip: 'Trasforma VetBuddy in "HubSpot Analytics per veterinari". Decision-making data-driven professionale.' },
    { icon: Zap, title: 'Marketing Automation Avanzato', color: 'bg-yellow-700', content: ['Funnel multi-step personalizzati (lead → cliente fedele)', 'Email sequences automatiche con trigger comportamentali', 'Lead scoring 0-100 per prioritizzazione', 'A/B testing automatico messaggi e landing pages', 'Segmentazione avanzata clienti'], tip: 'HubSpot-like per veterinari. Funnel completi, lead nurturing, conversion optimization automatica.' },
    { icon: Users, title: 'Gestione HR/Personale', color: 'bg-slate-700', content: ['Badge presenze automatico con rilevazione', 'Richieste ferie/permessi digitali con approvazioni', 'Generazione buste paga integrata', 'Piani formazione staff e tracking corsi', 'Valutazioni performance periodiche'], tip: 'Ideale per cliniche con 5+ dipendenti. Professionalizza gestione personale e riduce burocrazia.' },
    { icon: ShoppingCart, title: 'E-commerce Prodotti Pet', color: 'bg-pink-700', content: ['Vendita online cibo, antiparassitari, accessori', 'Integrazione inventario magazzino', 'Spedizioni automatiche con tracking', 'Marketing prodotti con email automatiche', 'Revenue addizionale 10-15% fatturato'], tip: 'I clienti acquistano dalla clinica di fiducia. E-commerce genera revenue passivo ricorrente.' },
    { icon: Home, title: 'Visite Domiciliari', color: 'bg-amber-700', content: ['Booking visite a casa con disponibilità veterinari', 'Tragitto giornaliero ottimizzato Google Maps', 'App mobile veterinario con cartelle offline', 'Pagamento e fatturazione automatica post-visita', 'Servizio premium €150-200/visita'], tip: 'Margini molto alti. Ideale per clienti anziani, disabili, animali difficili da trasportare.' },
    { icon: Apple, title: 'Nutrizione Personalizzata AI', color: 'bg-lime-700', content: ['Algoritmo AI piano alimentare per razza/età/peso/patologie', 'Tracking peso con grafici progressione', 'Alert automatici obesità e sottopeso', 'Prevenzione patologie croniche (diabete, obesità)', 'Riduce visite emergenza e migliora wellness'], tip: 'Medicina preventiva AI. Previene patologie prima che diventino emergenze costose per proprietario.' },
    { icon: Brain, title: 'AI Diagnostico Assistant', color: 'bg-purple-700', content: ['Inserisci sintomi osservati (vomito, letargia, anoressia)', 'AI analizza e suggerisce diagnosi differenziali per probabilità', 'Per ogni diagnosi: esami consigliati e livello urgenza', 'Basato su database migliaia di casi clinici veterinari', 'DISCLAIMER: supporto decisionale, NON sostituisce giudizio clinico'], tip: 'GAME CHANGER assoluto. NESSUN competitor ha AI diagnostico vero. Riduce errori del 30%.' },
    { icon: Video, title: 'Telemedicina Conforme FNOVI', color: 'bg-blue-700', content: ['Video-consulti HD SOLO per follow-up (non prime visite)', 'Conforme normativa FNOVI 2024', 'Registrazione automatica con consenso informato', 'Prescrizioni digitali post-consulto', 'Ideale: controlli terapia, dimissioni, follow-up semplici'], tip: 'Standard post-COVID. Risparmia tempo clinica e comodo per proprietari anziani/lontani.' },
    { icon: Watch, title: 'Pet Wearables & IoT Integration', color: 'bg-cyan-700', content: ['Connetti FitBark, Whistle, Tractive, Fi Collar, Petpace', 'Dati attività, sonno, calorie, GPS → cartella clinica 24/7', 'Grafici trend salute long-term automatici', 'Alert anomalie comportamentali (es: calo attività improvviso)', 'Dati oggettivi per diagnosi e monitoraggio terapie'], tip: 'IoT veterinario è il futuro. Dati oggettivi 24/7 battono sintomi soggettivi proprietario.' },
    { icon: ShieldCheck, title: 'Pet Insurance White-Label', color: 'bg-emerald-700', content: ['Vendi assicurazioni pet con TUO brand (Clinica X Insurance)', 'Backend assicurativo: UnipolSai (gestisce rischio)', 'Revenue share: 20% clinica, 10% VetBuddy, 70% assicuratore', '3 piani: Basic €19.90, Plus €39.90, Premium €59.90/mese', 'Claims automatici già integrati in VetBuddy'], tip: 'Nuovo revenue stream ENORME. 45 polizze = €1800/mese ricorrente. Clienti assicurati spendono +40%.' },
    { icon: Siren, title: 'Emergency Network 24/7', color: 'bg-red-700', content: ['Rete solidale: cliniche si aiutano su emergenze fuori competenza', 'SOS: lanci alert → altre rispondono disponibilità real-time', 'Sistema crediti: chi aiuta accumula, chi chiede usa (equilibrio)', 'Trasferimento paziente tracciato con follow-up automatico', 'Rete Milano/Roma/Torino attiva'], tip: 'Nessuna clinica può gestire ogni emergenza. Rete = sicurezza + solidarietà professionale.' },
    { icon: Briefcase, title: 'Veterinary Marketplace (Uber Vet)', color: 'bg-indigo-700', content: ['Trova veterinari sostituti/freelance per ferie/malattia/picchi', 'Tutti certificati FNOVI, assicurati, background check', 'Rating clienti, specializzazioni, tariffe orarie', 'Pagamento e contratto gestito da VetBuddy (15% fee)', 'Problema ENORME risolto: trovare sostituti è difficilissimo'], tip: 'Uber per veterinari. Rivoluziona mercato sostituzioni. Win-win per cliniche e freelance.' },
    { icon: FlaskConical, title: 'Clinical Trials Platform', color: 'bg-teal-700', content: ['Università/pharma pubblicano trial clinici su VetBuddy', 'Candidati se hai pazienti idonei', 'Compenso €300-500/trial per clinica', 'Farmaci gratis per paziente + follow-up', 'Dati raccolti automaticamente, contributo scienza'], tip: 'Democratizza ricerca clinica veterinaria. Revenue extra + contributo scientifico.' },
    { icon: Mic, title: 'Voice Assistant Multilingua', color: 'bg-purple-600', content: ['Alexa: "Alexa, prenota visita per Luna da VetBuddy"', 'Google: "Ok Google, prenota appuntamento VetBuddy"', 'Multilingua: Italiano, Inglese, Spagnolo, Francese', 'Conferma vocale + SMS automatico', 'Ideale: proprietari anziani, turisti, mani occupate'], tip: 'Voice-first veterinario. Comodità assoluta. Proprietari anziani lo adorano.' },
    { icon: Heart, title: 'Pet Adoption Platform', color: 'bg-pink-700', content: ['Canili/gattili pubblicano animali in adozione', 'Proprietari cercano e richiedono adozione', 'Prima visita veterinaria GRATIS inclusa (clinica partner)', 'Follow-up automatico post-adozione per assistenza', 'Social responsibility + acquisizione clienti lifetime'], tip: 'Etico + business. Prima visita gratis acquisisce cliente per 10-15 anni. ROI altissimo.' },
    { icon: AlertTriangle, title: 'Predictive Hospitalization AI', color: 'bg-red-800', content: ['AI analizza cartella clinica + esami recenti + età/razza paziente', 'Calcola rischio ospedalizzazione 48-72h (accuratezza 87%)', 'Alert automatico veterinario con pazienti ad alto rischio', 'Suggerisce intervento preemptivo (richiama, esami urgenti)', 'Previene emergenze costose + salva vite'], tip: 'Risparmio medio €4.2k/anno per clinica. Proprietari felici perché previeni il peggio.' },
    { icon: Heart, title: 'Mental Wellness Hub for Vets', color: 'bg-pink-800', content: ['Test burnout anonimo settimanale per tutto lo staff', 'Terapia online h24 con psicologi specializzati settore veterinario', 'Community support peer-to-peer 2400+ vet', 'Alert precoce team leader se qualcuno sta male', 'Retention staff +40%'], tip: 'Burnout veterinari è ALTISSIMO (30% depressione). Differenziatore etico enorme. Cliniche attraggono talenti migliori.' },
    { icon: Shield, title: 'Veterinary Litigation Shield', color: 'bg-blue-800', content: ['Assicurazione professionale €650/anno (massimale €500k)', 'AI analizza cartelle e avvisa gap documentali rischiosi', 'Supporto legale h24 con avvocati specializzati diritto veterinario', 'Mediazione automatica con proprietari prima di causa', 'Peace of mind totale'], tip: 'Contenziosi costano €10-50k + stress. Investimento €650/anno = dormire tranquilli.' },
    { icon: Brain, title: 'Pet Behavior AI Profiling', color: 'bg-purple-800', content: ['Questionario comportamentale proprietario pre-visita', 'AI genera score ansia/aggressività 0-100 per paziente', 'Suggerisce protocollo gestione (feromoni, sedazione, Low Stress)', 'Badge "Paziente ansioso" visibile prima che entri', 'Sicurezza staff +60%, meno sedazioni inutili'], tip: 'Riduce morsi, stress e costi sedazione. Proprietari più soddisfatti perché animale gestito bene.' },
    { icon: Clock, title: 'VetBuddy Time Machine', color: 'bg-cyan-800', content: ['Carica foto animale oggi', 'Seleziona scenario: obesità, diabete, artrosi non trattati', 'AI genera simulazione 5-10 anni: A) SENZA intervento vs B) CON intervento', 'Mostra visivamente conseguenze obesità/patologie', 'Shock emotivo proprietario → compliance +80%'], tip: 'Effetto WOW pazzesco. Virale sui social. Medicina preventiva diventa facile da vendere.' },
    { icon: Wrench, title: 'Predictive Equipment Maintenance', color: 'bg-orange-800', content: ['Sensori IoT su attrezzature critiche (RX, ecografo, autoclave)', 'AI analizza pattern utilizzo + vibrazioni + età', 'Predice guasto 7-14 giorni prima (85% accuratezza)', 'Ordina pezzo ricambio automaticamente', 'Zero downtime operatorio'], tip: 'Risparmio €10-15k/anno. Chirurgie mai cancellate. Standard ospedaliero veterinario.' },
    { icon: Sparkles, title: 'Cross-Species Learning AI', color: 'bg-indigo-800', content: ['AI trained su 2.4M casi tutte specie (cane, gatto, cavallo, rettili, uccelli, esotici)', 'Transfer learning: trova casi simili in altre specie', 'Suggerisce terapie provate su specie affini', 'Accesso letteratura cross-species in 2 secondi', 'Risolvi casi impossibili fuori comfort zone'], tip: 'Veterinario diventa "supervet" anche su specie rare. Patologie rare risolte.' },
    { icon: GraduationCap, title: 'VetBuddy Residency Program', color: 'bg-slate-800', content: ['Matching mentor senior - resident per specialità', 'Video-call 1h/settimana + revisione casi clinici', 'Certificazione "VetBuddy Certified Resident" FNOVI (12 mesi)', '€200/mese vs €20-40k/anno residenze tradizionali', 'Revenue share: 70% mentor, 20% VetBuddy, 10% borsa studio'], tip: 'Democratizza formazione specialistica. Cliniche assumono vet meglio formati.' },
    { icon: Activity, title: 'Fisioterapia & Riabilitazione', color: 'bg-teal-800', content: ['MODALITÀ 1: In-House con protocolli guidati + video-esercizi 150+ per proprietari', 'MODALITÀ 2: Network marketplace centri specializzati con referral workflow', 'Tracking progressi con grafici real-time', 'Tecniche: idroterapia, TENS, laser, ultrasuoni, massoterapia', 'Recupero +40% più veloce. Revenue ricorrente €60/sessione'], tip: 'Post-chirurgia LCA: 12 sessioni × €60 = €720 revenue addizionale. Se non hai attrezzature, invia a centro partner.' },


    { icon: CreditCard, title: 'Abbonamento', color: 'bg-slate-500', content: ['Starter: €29/mese (1 utente, fino a 30 prenotazioni/mese)', 'Growth: €69/mese (fino a 5 utenti, tutti i moduli) — Consigliato', 'Pro: €99/mese (fino a 15 utenti, AI, piani salute, automazioni avanzate)', 'Pilot Milano: Growth gratuito 90 giorni', 'Pagamento sicuro con Stripe, annulla quando vuoi'], tip: 'Prezzi IVA esclusa. VetBuddy è una piattaforma enterprise completa con 82 moduli.' },
    { icon: AlertTriangle, title: 'Drug Interaction Checker', color: 'bg-red-900', content: ['Database completo farmaci veterinari', 'Controllo automatico interazioni farmaco-farmaco', 'Controindicazioni per razza/età/patologia', 'Alert real-time pre-prescrizione', 'Riduce errori farmacologici a zero'], tip: 'Sicurezza farmacologica totale. Previene reazioni avverse gravi e riduce responsabilità medico-legale.' },
    { icon: Brain, title: 'AI Vision Diagnostics', color: 'bg-cyan-900', content: ['Carica RX, Ecografie, TAC in piattaforma', 'AI identifica anomalie automaticamente', 'Suggerisce diagnosi differenziali con probabilità', 'Confronta con database migliaia casi simili', 'Secondo parere istantaneo 24/7'], tip: 'Riduce errori diagnostici imaging del 30%. Supporto decisionale h24 per imaging medico complesso.' },
    { icon: Watch, title: 'Remote Patient Monitoring', color: 'bg-blue-900', content: ['Monitoraggio parametri vitali (FC, FR, Temp, SpO₂)', 'Collari smart + sensori medicali integrati', 'Alert anomalie real-time al veterinario', 'Dashboard clinica con grafici trend long-term', 'Ideale post-chirurgia e pazienti cronici'], tip: 'Telemedicina avanzata livello ospedaliero. Monitoraggio continuo pazienti ad alto rischio.' },
    { icon: ShoppingCart, title: 'VetBuddy Pharmacy', color: 'bg-green-900', content: ['Farmacia online 24/7 integrata in piattaforma', 'Prescrizioni digitali → ordine automatico → spedizione casa', 'Subscription antiparassitari mensili automatici', 'Nuovo revenue stream ricorrente margine 30-40%', 'Clinica vende farmaci direttamente senza intermediari'], tip: 'Revenue passivo ricorrente enorme. Clienti acquistano dalla clinica di fiducia, non da Amazon.' },
    { icon: GraduationCap, title: 'VetBuddy Academy', color: 'bg-indigo-900', content: ['Piattaforma LMS formazione staff completa', 'Video-corsi accreditati ECM con certificazioni', 'Webinar live con esperti internazionali', 'Tracking automatico crediti ECM obbligatori', 'Crescita professionale costante team'], tip: 'Formazione continua interna professionale. 50 crediti ECM/anno obbligatori tracciati automaticamente.' },
    { icon: Database, title: 'Blockchain Health Records', color: 'bg-purple-900', content: ['Cartelle cliniche immutabili su blockchain', 'Condivisione sicura inter-clinica certificata', 'Portabilità dati garantita per sempre', 'Audit trail immutabile per conformità legale', 'Futuro: NFT passaporto sanitario unico'], tip: 'Tecnologia cutting-edge. Massima sicurezza dati e portabilità garantita. Standard futuro veterinaria.' },
    { icon: Users, title: 'VetBuddy Consult', color: 'bg-pink-900', content: ['Marketplace consulenze specialistiche video on-demand', 'Dermatologo, cardiologo, oncologo disponibili 24h', 'Revenue share: 70% specialista, 20% clinica, 10% VetBuddy', 'Risolvi casi complessi senza inviare paziente', 'Accesso expertise mondiale per ogni clinica'], tip: 'Marketplace Uber per consulenze. Clinica guadagna 20% su ogni consulto richiesto.' },
    { icon: Home, title: 'Smart Clinic Hub (IoT)', color: 'bg-slate-900', content: ['Sensori temperatura/umidità degenza automatici', 'Monitoraggio O₂/ECG pazienti ricoverati 24/7', 'Alert attrezzature malfunzionanti preventivo', 'Workflow automatizzato basato su sensori IoT', 'Clinica 4.0 completamente connessa'], tip: 'Standard ospedaliero veterinario. IoT clinica intelligente riduce errori e migliora sicurezza pazienti.' },
    { icon: Sparkles, title: 'Genetic Precision Medicine', color: 'bg-amber-900', content: ['Partnership laboratori genetica veterinaria', 'Test genomici razze: predisposizioni patologie ereditarie', 'Farmacogenetica: dosaggi farmaci personalizzati su DNA', 'Consulenza breeding responsabile per allevatori', 'Medicina preventiva genomica personalizzata'], tip: 'Futuro veterinaria personalizzata. Previene patologie prima manifestazione e ottimizza terapie su DNA.' },


    { icon: CreditCard, title: 'Abbonamento', color: 'bg-slate-500', content: ['Starter: \u20AC29/mese (1 utente, fino a 30 prenotazioni/mese)', 'Growth: \u20AC69/mese (fino a 5 utenti, tutti i moduli) \u2014 Consigliato', 'Pro: \u20AC99/mese (fino a 15 utenti, AI, piani salute, automazioni avanzate)', 'Pilot Milano: Growth gratuito 90 giorni', 'Pagamento sicuro con Stripe, annulla quando vuoi'], tip: 'Prezzi IVA esclusa. VetBuddy non \u00E8 un gestionale: \u00E8 un copilota operativo.' },
  ];

  const handleDownload = async () => {
    try {
      const response = await fetch('/api/tutorials/download?type=clinic');
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'VetBuddy_Guida_Cliniche.pdf';
      a.click();
      URL.revokeObjectURL(url);
    } catch (e) {
      console.error('Download error:', e);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-gray-800">Guida per Cliniche Veterinarie</h2>
          <p className="text-sm text-gray-500">Il copilota operativo che riduce le telefonate e aumenta le prenotazioni.</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={handleDownload}><Download className="h-4 w-4 mr-1" />Scarica PDF</Button>
          {onClose && <Button variant="ghost" size="sm" onClick={onClose}>Chiudi</Button>}
        </div>
      </div>

      <div className="grid gap-3">
        {sections.map((s, idx) => {
          const Icon = s.icon;
          const isOpen = activeSection === idx;
          return (
            <Card key={idx} className={`cursor-pointer transition ${isOpen ? 'ring-2 ring-coral-200' : ''}`} onClick={() => setActiveSection(isOpen ? null : idx)}>
              <CardContent className="p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className={`${s.color} p-2 rounded-lg text-white`}><Icon className="h-4 w-4" /></div>
                    <span className="font-medium text-sm text-gray-800">{s.title}</span>
                  </div>
                  <ChevronRight className={`h-4 w-4 text-gray-400 transition ${isOpen ? 'rotate-90' : ''}`} />
                </div>
                {isOpen && (
                  <div className="mt-3 pl-12 space-y-1">
                    {s.content.map((c, i) => (
                      <p key={i} className="text-xs text-gray-600 flex items-start gap-1.5"><span className="text-coral-400 mt-0.5">•</span>{c}</p>
                    ))}
                    {s.tip && <Badge variant="outline" className="mt-2 text-xs text-amber-700 bg-amber-50 border-amber-200">💡 {s.tip}</Badge>}
                  </div>
                )}
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
